# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 06:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_events', '0004_orderevent_rate_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=4)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_positions', to=settings.AUTH_USER_MODEL)),
                ('rate_card_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='order_events.RateCardPosition')),
            ],
            options={
                'ordering': ('customer', 'name'),
            },
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='rate_cards',
            field=models.ManyToManyField(related_name='orders', to='order_events.RateCard'),
        ),
    ]
