# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_events', '0006_auto_20170508_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderposition',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='order_events.OrderEvent'),
            preserve_default=False,
        ),
    ]
