# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_events', '0007_orderposition_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderposition',
            old_name='order',
            new_name='order_event',
        ),
    ]
