# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_events', '0008_auto_20170508_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderevent',
            name='participants',
            field=models.ManyToManyField(related_name='paricipated_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
