# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order_events', '0009_orderevent_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderevent',
            name='invitation_token',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
    ]
